### ISSUE TITLE
Mismatched data readings?

### ISSUE THREAD

**Issue by andriej** [mvn23/pyotgw#8]
I'm using OTGW integration in HA and it just works.
Lately I've been updating the UI and I've encountered something that I assume is not right.
Names are (yet) default from integration, might be easier to debug:

![image](https://user-images.githubusercontent.com/6303489/63911242-eff82e00-ca29-11e9-9cd9-1597e9f8701c.png)
![image](https://user-images.githubusercontent.com/6303489/63911265-043c2b00-ca2a-11e9-859a-be48e4a6b04b.png)
![image](https://user-images.githubusercontent.com/6303489/63911276-0ef6c000-ca2a-11e9-96e6-ef85290f8e5e.png)

Currently I've disabled the central heating as it's still summer and it's not needed. 
It can be seen that "Central Heating" (picture 1) pump starts counter is increasing while "hot water pump starts" (picture 3) is flat.
Shouldn't it be switched? We use hot water only so far. :-)

I'm wondering if it's fault of boiler or mismatch somewhere in the code.

**Comment by mvn23** [comment]
I see the same behavior here. However, after checking the code, I found that it matches the protocol specification I used (v2.2): message ID 117 (0x75) for CH pump starts and 118 (0x76) for hot water.

It is unlikely that this was changed between versions, so either the specification I have is incorrect or both of our boilers have implemented this the wrong way around. If I can find some proof for the former I will update the code accordingly.

**Comment by mvn23** [comment]
No progress in more than a year. While this bug is backed up by real-world examples in at least 2 cases (including my own), we do follow the OpenTherm spec with the current implementation.
Other software packages seem to deal with this in the same way. While this in itself is of course no valid reason to not change anything, I do want to mention it as an additional consideration.
Closing this for now, please feel free to open a new issue if and when new information becomes available.
